/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0ZjIX1RuhO5
 */
'use client'
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useQuery,useMutation } from "convex/react"
import { api } from "@/convex/_generated/api"
export function TasksUi() {
  const tasks = useQuery(api.tasks.get);
  const create = useMutation(api.tasks.send)
  const del = useMutation(api.tasks.del)
  async function createTask(formData: FormData) {
    const rawFormData = {
        text: formData.get('text'),
        isCompleted: false
      }
      console.log("hi");
      
      create({
          body: rawFormData.text as string,
      })
}
  return (

    <div className="flex flex-col">
      <main className="flex-1 p-4 md:p-6">
        <div className="space-y-4">
          {!tasks &&(
            <div className="text-emerald-700rounded-full text-center">No tasks</div>
          )}
        {tasks?.map(({ _id, text }) => (
          <div key={_id} className="flex items-center gap-4">
            <Checkbox id={_id} onChange={()=>{

            }} />
            <Label className="flex-1" htmlFor={_id}>
            {text}
            </Label>
            <Button size="sm" variant="outline" onClick={()=>{
              del({
                id: _id
              })
            }}>
              Delete
            </Button>
          </div>
      ))}
          <form className="flex items-center gap-4 mb-6" action={createTask}>
            <Input className="flex-1" placeholder="Add new task..." type="text" name="text" />
            <Button type="submit">Add Task</Button>
          </form>
        </div>
      </main>
    </div>
  )
}
